name: Vue Paper Dashboard CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 8.1.4
      WORKDIR: vue-paper-dashboard-master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Update npm
        run: npm install -g npm@latest

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        working-directory: ${{ env.WORKDIR }}
        run: npm install

      - name: Build project
        working-directory: ${{ env.WORKDIR }}
        run: npm run build

      - name: Run project
        working-directory: ${{ env.WORKDIR }}
        run: npm run dev &

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ env.WORKDIR }}/dist/**